# Generated by Django 3.2.19 on 2023-06-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], max_length=10)),
                ('type', models.CharField(choices=[('PAYMENT', 'PAYMENT'), ('FINE', 'FINE')], max_length=10)),
                ('borrowing_id', models.PositiveIntegerField()),
                ('session_url', models.URLField()),
                ('session_id', models.CharField(max_length=255)),
            ],
        ),
    ]
