# Generated by Django 3.2.19 on 2023-06-07 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0005_auto_20230606_1321'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='borrowing_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='borrowing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='borrowing.borrowing'),
        ),
        migrations.AddField(
            model_name='payment',
            name='to_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
