# Generated by Django 4.2.2 on 2023-06-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField(null=True)),
                ("expected_return_date", models.DateField()),
                ("actual_return_date", models.DateField(null=True)),
                ("book_id", models.PositiveIntegerField()),
                ("user_id", models.PositiveIntegerField()),
            ],
        ),
    ]
