# Generated by Django 3.2.19 on 2023-06-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_borrowing_borrowed_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='borrowed_book',
        ),
    ]
