# Generated by Django 3.2.19 on 2023-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_remove_borrowing_borrowed_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='book_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
