# Generated by Django 4.2.2 on 2023-06-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
